version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.06.2-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv --force /tmp/docker/* /usr/bin
      - deploy:
          command: |
            docker build -t bigboat/monitor .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push bigboat/monitor
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              docker tag bigboat/monitor bigboat/monitor:${CIRCLE_TAG}
              docker push bigboat/monitor:${CIRCLE_TAG}
            fi
